# GitHub Actions для сборки Android APK
# Простая версия без сложных зависимостей

name: Build APK
on: [push]

jobs:
  build-android:
    name: Build for Android
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y git zip unzip python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev automake gettext libltdl-dev
          python -m pip install --upgrade pip
          pip install --user Cython virtualenv buildozer

      - name: Build APK
        run: |
          export PATH=$PATH:~/.local/bin/
          export JAVA_HOME=/usr/lib/jvm/temurin-17-jdk-amd64
          export PATH=$JAVA_HOME/bin:$PATH
          yes | buildozer -v android debug

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: bin/*.apk